export const TableActions = {
    SET_DATA: 'SET_DATA',
    SET_LOADING: 'SET_LOADING',
    TO_NEXT_PAGE: 'TO_NEXT_PAGE',
    TO_PREV_PAGE: 'TO_PREV_PAGE',
    TO_FIRST_PAGE: 'TO_FIRST_PAGE',
    TO_LAST_PAGE: 'TO_LAST_PAGE',
    SEARCH: 'SEARCH',
    SORT: 'SORT',
}
